data:
  dataset:
    name: officehome # choices are ['office', 'officehome', 'caltech-imagenet', 'visda2017']
    root_path: /home/youkaichao/data/Office_Home # /path/to/dataset/root
    source: 0 # source domain index
    target: 1 # target domain index
    n_share: 10 # number of classes to be shared
    n_source_private: 5 # number of classes in source private domain
    n_total: 65 # number of classes in total

  dataloader:
    class_balance: true #
    data_workers: 3 # how many workers to use for train dataloaders
    batch_size: 36 # batch_size for source domain and target domain respectively

model:
  base_model: resnet50 # choices=['resnet50', 'vgg16']
  pretrained_model: /home/youkaichao/data/pytorchModels/resnet50.pth # /path/to/pretrained/model

train:
  min_step: 40000 # minimum steps to run. run epochs until it exceeds the minStep
  lr: 0.01 # learning rate for new layers. learning rate for finetune is 1/10 of lr
  weight_decay: 0.0005
  momentum: 0.9

test:
  test_interval: 500 # interval of two continuous test phase
  test_only: False # test a given model and exit
  resume_file: '' # model to test
  w_0: -0.5 # hyper-parameter w_0

misc:
  gpus: 1 # how many GPUs to be used, 0 indicates CPU only

log:
  root_dir: log # the log directory (log directory will be {root_dir}/{method}/time/)
  log_interval: 10 # steps to log scalars